#!/usr/local/bin/bash

# Start a dev tmux session with all repos opened in windows
tmux new -s Dev -n bees \;  \
  send-keys 'cd projects/bees' C-m \; \
  new-window -n hbcrm -t Dev: \; \
  send-keys 'cd projects/hbcrm' C-m \; \
  new-window -n pd -t Dev: \; \
  send-keys 'cd projects/pd' C-m \; \
  new-window -n hb-ansible -t Dev: \; \
  send-keys 'cd projects/hb-ansible' C-m \; \
  new-window -n hb-buzz -t Dev: \; \
  send-keys 'cd projects/hb-buzz' C-m \; \
  new-window -n bees-infra -t Dev: \; \
  send-keys 'cd projects/bees-infra' C-m \; \
  new-window -n pd-infra -t Dev: \; \
  send-keys 'cd projects/pd-infra' C-m \; \
  new-window -n terraform-modules -t Dev: \; \
  send-keys 'cd projects/terraform-modules' C-m \;
